# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux/Qt6', 'Linux/Qt6Next', 'FreeBSD/Qt6', 'Windows/Qt6', 'Android/Qt6']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kguiaddons': '@latest-kf6'

 - 'on': ['Android/Qt6']
   'require':
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kconfigwidgets': '@latest-kf6'
    'frameworks/kirigami': '@latest-kf6'
    'libraries/kirigami-addons': '@latest-kf6'

 - 'on': ['Linux/Qt6', 'Linux/Qt6Next', 'FreeBSD/Qt6', 'Windows/Qt6']
   'require':
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'

Options:
 require-passing-tests-on: ['@all']
